package com.example.besonapp.util

object AnimationConstants {

    //COMMON
    const val APP_EXPLAINING_TAPE_OFFSET_DELAY = 2000
    const val APP_EXPLAINING_TAPE_OFFSET_DURATION = 1500

    //SPLASH SCREEN
    const val SPLASH_SCREEN_DELAY = 7800

    const val SPLASH_SCREEN_LOGO_ANIMATION_ALPHA_DELAY = 0
    const val SPLASH_SCREEN_LOGO_ANIMATION_ALPHA_DURATION = 2000

    const val SPLASH_SCREEN_LOGO_ANIMATION_ROTATE_DELAY = 0
    const val SPLASH_SCREEN_LOGO_ANIMATION_ROTATE_DURATION = 800

    const val SPLASH_SCREEN_LOGO_ANIMATION_ALPHA_AGAIN_DELAY = 0
    const val SPLASH_SCREEN_LOGO_ANIMATION_ALPHA_AGAIN_DURATION = 2000

    //INTRO SCREEN - DISABLED

    const val INTRO_SCREEN_ENTER_TRANSITION_ANIMATION_DURATION = 1000
    const val INTRO_SCREEN_EXIT_TRANSITION_ANIMATION_DURATION = 1000

    const val INTRO_SCREEN_LOGO_ANIMATION_ROTATE_DELAY = 0
    const val INTRO_SCREEN_LOGO_ANIMATION_ROTATE_DURATION = 800

    const val INTRO_SCREEN_LOGO_ANIMATION_SIZE_DELAY = 0
    const val INTRO_SCREEN_LOGO_ANIMATION_SIZE_DURATION = 2000

    const val INTRO_SCREEN_LOGO_ANIMATION_PADDING_BOTTOM_DELAY = 0
    const val INTRO_SCREEN_LOGO_ANIMATION_PADDING_BOTTOM_DURATION = 1500

    const val INTRO_SCREEN_LOGO_ANIMATION_PADDING_END_DELAY = 0
    const val INTRO_SCREEN_LOGO_ANIMATION_PADDING_END_DURATION = 2000

    const val INTRO_SCREEN_LOGO_ANIMATION_TEXT_ALPHA_DELAY = 0
    const val INTRO_SCREEN_LOGO_ANIMATION_TEXT_ALPHA_DURATION = 1000
}